<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>dvmig.XTB</AssemblyName>
    <RootNamespace>dvmig.XTB</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="XrmToolBoxPackage" Version="1.2023.10.67" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\dvmig.Core\dvmig.Core.csproj" />
  </ItemGroup>

</Project>
